Vagrant.configure("2") do |config|
  config.vm.box = "opscode-centos-7.0"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"
  config.omnibus.chef_version = :latest
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.berkshelf.enabled = true

  config.vm.provision :chef_client do |chef|
    chef.provisioning_path = "/etc/chef"
    chef.chef_server_url = "https://api.chef.io/organizations/omegacorp"
    chef.validation_key_path = "/Users/omegabk/Documents/Chef_Stuff/omega_learn_chef/chef-repo/.chef/omegacorp-validator.pem"
    chef.validation_client_name = "omegacorp-validator"
    chef.node_name = "server"
  end
end
